spring:
  datasource:
    url: jdbc:mysql://www.passerby.fun:3306/colloa?characterEncoding=utf-8
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver